version: "3.9"
   
services:
  pocketbase:
    build:
      context: .
      dockerfile: ./pocketbase/Dockerfile
    volumes:
      - totallyMetal:/pb/pb_data
    ports:
      - "127.0.0.1:8082:8080"
  scraper:
    build:
      context: .
      dockerfile: ./src/Dockerfile
    depends_on:
      - pocketbase
volumes:
  totallyMetal:
    name: 'totallyMetal'